### ISSUE TITLE
ProcessException: The system cannot find the file specified

### ISSUE THREAD

**Issue by garysm** [kevmoo/shelf_dev#20]
Encountered error when running **shelf_dev** command, version 2.0.1.

shelf_dev.yaml:

```yaml
web-app:
  path: app
  command: flutter run -d web-server --web-port {PORT}

web-server:
  path: server
  command: dart bin/server.dart --port {PORT}
  source: api
```

Console Output:

```console
server exit   -1
An error occurred!
ProcessException: The system cannot find the file specified.

  Command: flutter run -d web-server --web-port 56632
dart:io
                       Process.start
package:shelf_dev/src/server_wrapper.dart 195:35
                       ServerWrapper._doRunningTransition
package:shelf_dev/src/server_wrapper.dart 153:17
                       ServerWrapper._gotoState
package:shelf_dev/src/server_wrapper.dart 106:11
                       ServerWrapper._startProcess
package:shelf_dev/src/server_wrapper.dart 77:19
                       ServerWrapper.create
package:shelf_dev/src/runner.dart 91:33
                       run
..\..\..\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shelf_dev-2.0.1\bin\shelf_dev.dart 16:5  main
```

Both commands work in their respective directories.

EDIT: Command works on Linux, but not Windows
